# Generated by Django 6.1 on 2026-09-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
